import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Building2, CircleHelp, HeartHandshake, MapPin, Newspaper, Quote, Stethoscope, UserRound } from "lucide-react";
import { PublicPage } from "@/components/layout/public-page";
import { SectionHeading, UnpublishedPanel } from "@/components/shared/page";
import { Button } from "@/components/ui/button";
import { siteConfig } from "@/config/site";
import { articles, doctors, facilities, faqs, reviews, services } from "@/content/placeholders";
import { createPageMeta } from "@/lib/seo";

export const Route = createFileRoute("/")({ head: () => ({ meta: createPageMeta("Home", "Welcome to The Millennium Hospital. Explore care information, hospital services, facilities, and ways to contact the team.") }), component: HomePage });
const professionalServices = services.filter((service) => service.type === "professional");
const hospitalServices = services.filter((service) => service.type === "hospital");

function HomeSection({ children, muted = false, id }: { children: React.ReactNode; muted?: boolean; id: string }) {
  return <section id={id} className={muted ? "border-y border-border bg-surface" : "bg-background"}><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8">{children}</div></section>;
}

function Preview({ count, singular, empty }: { count: number; singular: string; empty: string }) {
  return count ? <p className="mt-8 text-sm text-muted-foreground">{count} published {count === 1 ? singular : `${singular}s`}</p> : <UnpublishedPanel title={`No ${singular}s published yet`} description={empty} />;
}

function HomePage() {
  return <PublicPage>
    <section className="relative overflow-hidden bg-hero text-primary-foreground"><div className="absolute inset-y-0 right-0 hidden w-[38%] border-l border-primary-foreground/10 bg-primary-foreground/5 lg:block"/><div className="relative mx-auto grid min-h-[600px] max-w-7xl items-center gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.25fr_.75fr] lg:px-8"><div><p className="text-sm font-semibold text-highlight">Welcome to {siteConfig.name}</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[1.08] sm:text-6xl">Care that listens. Expertise you can trust.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-primary-foreground/75">Find clear hospital information and the right next step for your care.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" className="bg-highlight text-highlight-foreground hover:bg-highlight/90"><Link to="/doctors">Find a doctor <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline" className="border-primary-foreground/30 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><Link to="/contact">Make an enquiry</Link></Button></div></div><div className="grid gap-px border border-primary-foreground/15 bg-primary-foreground/15"><div className="bg-hero p-6"><HeartHandshake className="text-highlight"/><h2 className="mt-5 text-xl font-semibold">Patient-first information</h2><p className="mt-2 text-sm leading-6 text-primary-foreground/70">Simple routes to care, facilities, and hospital support.</p></div><div className="bg-hero p-6"><Stethoscope className="text-highlight"/><h2 className="mt-5 text-xl font-semibold">Clinically reviewed content</h2><p className="mt-2 text-sm leading-6 text-primary-foreground/70">Profiles and information appear only after approval.</p></div></div></div></section>
    <HomeSection id="introduction"><SectionHeading eyebrow="The hospital" title="Thoughtful care, built around people" description="The hospital’s verified story, approach, and patient commitments will be published here." link={{ label: "About the hospital", to: "/about" }}/></HomeSection>
    <HomeSection id="departments" muted><SectionHeading eyebrow="Departments & specialties" title="Find the right area of care" description="Department and specialty information will be easy to browse once approved." link={{ label: "Browse doctors", to: "/doctors" }}/><UnpublishedPanel title="Departments are being prepared" description="No department or specialty information has been published yet."/></HomeSection>
    <HomeSection id="professional-services"><SectionHeading eyebrow="Professional services" title="Specialist support for your care" description="Professional services will be listed separately so patients can quickly understand what is available." link={{ label: "Explore services", to: "/services" }}/><Preview count={professionalServices.length} singular="professional service" empty="Verified professional service information will appear here."/></HomeSection>
    <HomeSection id="hospital-services" muted><SectionHeading eyebrow="Hospital services" title="Care across the hospital" description="Hospital-wide clinical and support services will appear here after review." link={{ label: "View hospital services", to: "/services" }}/><Preview count={hospitalServices.length} singular="hospital service" empty="Verified hospital service information will appear here."/></HomeSection>
    <HomeSection id="doctors"><SectionHeading eyebrow="Medical team" title="Meet our doctors" description="Search verified clinician profiles by name, specialty, or department." link={{ label: "Find a doctor", to: "/doctors" }}/><Preview count={doctors.length} singular="doctor profile" empty="Clinician profiles are awaiting review and publication."/></HomeSection>
    <HomeSection id="facilities" muted><SectionHeading eyebrow="Hospital environment" title="Facilities designed for care" description="See practical, approved information to help prepare for your visit." link={{ label: "Explore facilities", to: "/facilities" }}/><Preview count={facilities.length} singular="facility" empty="Facility details and approved images are being prepared."/></HomeSection>
    <HomeSection id="reviews"><SectionHeading eyebrow="Patient voices" title="Verified patient experiences" description="Only reviewed and approved patient feedback will be displayed." link={{ label: "Read reviews", to: "/reviews" }}/><Preview count={reviews.length} singular="review" empty="No patient reviews are published yet."/></HomeSection>
    <HomeSection id="faq" muted><SectionHeading eyebrow="Practical answers" title="Frequently asked questions" description="Clear information for patients, families, and visitors." link={{ label: "View all questions", to: "/faq" }}/><Preview count={faqs.length} singular="answer" empty="Answers are being prepared for publication."/></HomeSection>
    <HomeSection id="media"><SectionHeading eyebrow="Media & content" title="Hospital news and health resources" description="Read hospital updates and clinically reviewed information." link={{ label: "Browse resources", to: "/blog" }}/><Preview count={articles.length} singular="article" empty="No articles have been published yet."/></HomeSection>
    <HomeSection id="location" muted><div className="grid gap-10 lg:grid-cols-2"><SectionHeading eyebrow="Location & contact" title="Plan your visit" description="Verified address, phone, email, WhatsApp, and map information will be shown here." link={{ label: "Contact information", to: "/contact" }}/><div className="grid min-h-56 place-items-center border border-dashed border-border bg-background text-center"><div><MapPin className="mx-auto text-primary"/><p className="mt-3 font-semibold">Location not yet published</p><p className="mt-2 text-sm text-muted-foreground">A map will appear after the address is verified.</p></div></div></div></HomeSection>
    <section className="bg-hero text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-4 py-16 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><div><p className="text-sm font-semibold text-highlight">Appointments & enquiries</p><h2 className="mt-3 text-3xl font-semibold">How can we help you today?</h2><p className="mt-3 text-primary-foreground/70">Contact the hospital for current care and appointment information.</p></div><Button asChild size="lg" className="bg-highlight text-highlight-foreground hover:bg-highlight/90"><Link to="/contact">Contact the hospital <ArrowRight/></Link></Button></div></section>
  </PublicPage>;
}