/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/[_]admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MediaRouteImport } from './routes/media'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AdminIndexRouteImport } from './routes/[_]admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/[_]admin.audit-logs'
import { Route as AdminBlogRouteImport } from './routes/[_]admin.blog'
import { Route as AdminBlogCommentsRouteImport } from './routes/[_]admin.blog-comments'
import { Route as AdminDashboardRouteImport } from './routes/[_]admin.dashboard'
import { Route as AdminDepartmentsRouteImport } from './routes/[_]admin.departments'
import { Route as AdminDoctorsRouteImport } from './routes/[_]admin.doctors'
import { Route as AdminEnquiriesRouteImport } from './routes/[_]admin.enquiries'
import { Route as AdminFacilitiesRouteImport } from './routes/[_]admin.facilities'
import { Route as AdminFaqCategoriesRouteImport } from './routes/[_]admin.faq-categories'
import { Route as AdminFaqsRouteImport } from './routes/[_]admin.faqs'
import { Route as AdminHospitalServicesRouteImport } from './routes/[_]admin.hospital-services'
import { Route as AdminLocationsRouteImport } from './routes/[_]admin.locations'
import { Route as AdminLoginRouteImport } from './routes/[_]admin.login'
import { Route as AdminMediaRouteImport } from './routes/[_]admin.media'
import { Route as AdminNavigationRouteImport } from './routes/[_]admin.navigation'
import { Route as AdminNotificationsRouteImport } from './routes/[_]admin.notifications'
import { Route as AdminPagesRouteImport } from './routes/[_]admin.pages'
import { Route as AdminProfessionalServicesRouteImport } from './routes/[_]admin.professional-services'
import { Route as AdminProfileRequestsRouteImport } from './routes/[_]admin.profile-requests'
import { Route as AdminReviewsRouteImport } from './routes/[_]admin.reviews'
import { Route as AdminSeoRouteImport } from './routes/[_]admin.seo'
import { Route as AdminSeoAnalyticsRouteImport } from './routes/[_]admin.seo-analytics'
import { Route as AdminSeoAuditRouteImport } from './routes/[_]admin.seo-audit'
import { Route as AdminSeoHistoryRouteImport } from './routes/[_]admin.seo-history'
import { Route as AdminSeoKeywordsRouteImport } from './routes/[_]admin.seo-keywords'
import { Route as AdminSeoLocalRouteImport } from './routes/[_]admin.seo-local'
import { Route as AdminSeoTargetsRouteImport } from './routes/[_]admin.seo-targets'
import { Route as AdminSeoTechnicalRouteImport } from './routes/[_]admin.seo-technical'
import { Route as AdminUsersRouteImport } from './routes/[_]admin.users'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as DepartmentsSlugRouteImport } from './routes/departments.$slug'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsSlugRouteImport } from './routes/doctors.$slug'
import { Route as FacilitiesIndexRouteImport } from './routes/facilities.index'
import { Route as FacilitiesSlugRouteImport } from './routes/facilities.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AdminBlogCommentsIndexRouteImport } from './routes/[_]admin.blog-comments.index'
import { Route as AdminBlogCommentsCommentIdRouteImport } from './routes/[_]admin.blog-comments.$commentId'
import { Route as AdminBlogIndexRouteImport } from './routes/[_]admin.blog.index'
import { Route as AdminDepartmentsIndexRouteImport } from './routes/[_]admin.departments.index'
import { Route as AdminDoctorsIndexRouteImport } from './routes/[_]admin.doctors.index'
import { Route as AdminProfileRequestsRequestIdRouteImport } from './routes/[_]admin.profile-requests.$requestId'
import { Route as AdminSeoKeywordKeywordIdRouteImport } from './routes/[_]admin.seo-keyword.$keywordId'
import { Route as AdminSeoTargetTargetIdRouteImport } from './routes/[_]admin.seo-target.$targetId'
import { Route as AdminUsersUserIdRouteImport } from './routes/[_]admin.users.$userId'
import { Route as ApiPublicDoctorProfileImageRouteImport } from './routes/api/public/doctor-profile-image'
import { Route as ApiPublicDoctorVcardRouteImport } from './routes/api/public/doctor-vcard'
import { Route as ServicesHospitalSlugRouteImport } from './routes/services.hospital.$slug'
import { Route as ServicesProfessionalSlugRouteImport } from './routes/services.professional.$slug'
import { Route as AdminBlogPostIdSectionRouteImport } from './routes/[_]admin.blog.$postId.$section'
import { Route as AdminContentContentTypeRecordIdRouteImport } from './routes/[_]admin.content.$contentType.$recordId'
import { Route as AdminDepartmentsDepartmentIdSectionRouteImport } from './routes/[_]admin.departments.$departmentId.$section'
import { Route as AdminDoctorsDoctorIdSectionRouteImport } from './routes/[_]admin.doctors.$doctorId.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  path: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCommentsRoute = AdminBlogCommentsRouteImport.update({
  id: '/blog-comments',
  path: '/blog-comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqCategoriesRoute = AdminFaqCategoriesRouteImport.update({
  id: '/faq-categories',
  path: '/faq-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHospitalServicesRoute = AdminHospitalServicesRouteImport.update({
  id: '/hospital-services',
  path: '/hospital-services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessionalServicesRoute =
  AdminProfessionalServicesRouteImport.update({
    id: '/professional-services',
    path: '/professional-services',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProfileRequestsRoute = AdminProfileRequestsRouteImport.update({
  id: '/profile-requests',
  path: '/profile-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoAnalyticsRoute = AdminSeoAnalyticsRouteImport.update({
  id: '/seo-analytics',
  path: '/seo-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoAuditRoute = AdminSeoAuditRouteImport.update({
  id: '/seo-audit',
  path: '/seo-audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoHistoryRoute = AdminSeoHistoryRouteImport.update({
  id: '/seo-history',
  path: '/seo-history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoKeywordsRoute = AdminSeoKeywordsRouteImport.update({
  id: '/seo-keywords',
  path: '/seo-keywords',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoLocalRoute = AdminSeoLocalRouteImport.update({
  id: '/seo-local',
  path: '/seo-local',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoTargetsRoute = AdminSeoTargetsRouteImport.update({
  id: '/seo-targets',
  path: '/seo-targets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoTechnicalRoute = AdminSeoTechnicalRouteImport.update({
  id: '/seo-technical',
  path: '/seo-technical',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepartmentsRoute,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DepartmentsRoute,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorsRoute,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DoctorsRoute,
} as any)
const FacilitiesIndexRoute = FacilitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacilitiesRoute,
} as any)
const FacilitiesSlugRoute = FacilitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FacilitiesRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminBlogCommentsIndexRoute = AdminBlogCommentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogCommentsRoute,
} as any)
const AdminBlogCommentsCommentIdRoute =
  AdminBlogCommentsCommentIdRouteImport.update({
    id: '/$commentId',
    path: '/$commentId',
    getParentRoute: () => AdminBlogCommentsRoute,
  } as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminDepartmentsIndexRoute = AdminDepartmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDepartmentsRoute,
} as any)
const AdminDoctorsIndexRoute = AdminDoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDoctorsRoute,
} as any)
const AdminProfileRequestsRequestIdRoute =
  AdminProfileRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => AdminProfileRequestsRoute,
  } as any)
const AdminSeoKeywordKeywordIdRoute =
  AdminSeoKeywordKeywordIdRouteImport.update({
    id: '/seo-keyword/$keywordId',
    path: '/seo-keyword/$keywordId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSeoTargetTargetIdRoute = AdminSeoTargetTargetIdRouteImport.update({
  id: '/seo-target/$targetId',
  path: '/seo-target/$targetId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ApiPublicDoctorProfileImageRoute =
  ApiPublicDoctorProfileImageRouteImport.update({
    id: '/api/public/doctor-profile-image',
    path: '/api/public/doctor-profile-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDoctorVcardRoute = ApiPublicDoctorVcardRouteImport.update({
  id: '/api/public/doctor-vcard',
  path: '/api/public/doctor-vcard',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHospitalSlugRoute = ServicesHospitalSlugRouteImport.update({
  id: '/hospital/$slug',
  path: '/hospital/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesProfessionalSlugRoute =
  ServicesProfessionalSlugRouteImport.update({
    id: '/professional/$slug',
    path: '/professional/$slug',
    getParentRoute: () => ServicesRoute,
  } as any)
const AdminBlogPostIdSectionRoute = AdminBlogPostIdSectionRouteImport.update({
  id: '/$postId/$section',
  path: '/$postId/$section',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminContentContentTypeRecordIdRoute =
  AdminContentContentTypeRecordIdRouteImport.update({
    id: '/content/$contentType/$recordId',
    path: '/content/$contentType/$recordId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDepartmentsDepartmentIdSectionRoute =
  AdminDepartmentsDepartmentIdSectionRouteImport.update({
    id: '/$departmentId/$section',
    path: '/$departmentId/$section',
    getParentRoute: () => AdminDepartmentsRoute,
  } as any)
const AdminDoctorsDoctorIdSectionRoute =
  AdminDoctorsDoctorIdSectionRouteImport.update({
    id: '/$doctorId/$section',
    path: '/$doctorId/$section',
    getParentRoute: () => AdminDoctorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/doctors': typeof DoctorsRouteWithChildren
  '/facilities': typeof FacilitiesRouteWithChildren
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/blog': typeof AdminBlogRouteWithChildren
  '/_admin/blog-comments': typeof AdminBlogCommentsRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/departments': typeof AdminDepartmentsRouteWithChildren
  '/_admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/_admin/enquiries': typeof AdminEnquiriesRoute
  '/_admin/facilities': typeof AdminFacilitiesRoute
  '/_admin/faq-categories': typeof AdminFaqCategoriesRoute
  '/_admin/faqs': typeof AdminFaqsRoute
  '/_admin/hospital-services': typeof AdminHospitalServicesRoute
  '/_admin/locations': typeof AdminLocationsRoute
  '/_admin/login': typeof AdminLoginRoute
  '/_admin/media': typeof AdminMediaRoute
  '/_admin/navigation': typeof AdminNavigationRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/pages': typeof AdminPagesRoute
  '/_admin/professional-services': typeof AdminProfessionalServicesRoute
  '/_admin/profile-requests': typeof AdminProfileRequestsRouteWithChildren
  '/_admin/reviews': typeof AdminReviewsRoute
  '/_admin/seo': typeof AdminSeoRoute
  '/_admin/seo-analytics': typeof AdminSeoAnalyticsRoute
  '/_admin/seo-audit': typeof AdminSeoAuditRoute
  '/_admin/seo-history': typeof AdminSeoHistoryRoute
  '/_admin/seo-keywords': typeof AdminSeoKeywordsRoute
  '/_admin/seo-local': typeof AdminSeoLocalRoute
  '/_admin/seo-targets': typeof AdminSeoTargetsRoute
  '/_admin/seo-technical': typeof AdminSeoTechnicalRoute
  '/_admin/users': typeof AdminUsersRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/facilities/$slug': typeof FacilitiesSlugRoute
  '/_admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/facilities/': typeof FacilitiesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_admin/blog-comments/$commentId': typeof AdminBlogCommentsCommentIdRoute
  '/_admin/profile-requests/$requestId': typeof AdminProfileRequestsRequestIdRoute
  '/_admin/seo-keyword/$keywordId': typeof AdminSeoKeywordKeywordIdRoute
  '/_admin/seo-target/$targetId': typeof AdminSeoTargetTargetIdRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/doctor-profile-image': typeof ApiPublicDoctorProfileImageRoute
  '/api/public/doctor-vcard': typeof ApiPublicDoctorVcardRoute
  '/services/hospital/$slug': typeof ServicesHospitalSlugRoute
  '/services/professional/$slug': typeof ServicesProfessionalSlugRoute
  '/_admin/blog-comments/': typeof AdminBlogCommentsIndexRoute
  '/_admin/blog/': typeof AdminBlogIndexRoute
  '/_admin/departments/': typeof AdminDepartmentsIndexRoute
  '/_admin/doctors/': typeof AdminDoctorsIndexRoute
  '/_admin/blog/$postId/$section': typeof AdminBlogPostIdSectionRoute
  '/_admin/content/$contentType/$recordId': typeof AdminContentContentTypeRecordIdRoute
  '/_admin/departments/$departmentId/$section': typeof AdminDepartmentsDepartmentIdSectionRoute
  '/_admin/doctors/$doctorId/$section': typeof AdminDoctorsDoctorIdSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/enquiries': typeof AdminEnquiriesRoute
  '/_admin/facilities': typeof AdminFacilitiesRoute
  '/_admin/faq-categories': typeof AdminFaqCategoriesRoute
  '/_admin/faqs': typeof AdminFaqsRoute
  '/_admin/hospital-services': typeof AdminHospitalServicesRoute
  '/_admin/locations': typeof AdminLocationsRoute
  '/_admin/login': typeof AdminLoginRoute
  '/_admin/media': typeof AdminMediaRoute
  '/_admin/navigation': typeof AdminNavigationRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/pages': typeof AdminPagesRoute
  '/_admin/professional-services': typeof AdminProfessionalServicesRoute
  '/_admin/profile-requests': typeof AdminProfileRequestsRouteWithChildren
  '/_admin/reviews': typeof AdminReviewsRoute
  '/_admin/seo': typeof AdminSeoRoute
  '/_admin/seo-analytics': typeof AdminSeoAnalyticsRoute
  '/_admin/seo-audit': typeof AdminSeoAuditRoute
  '/_admin/seo-history': typeof AdminSeoHistoryRoute
  '/_admin/seo-keywords': typeof AdminSeoKeywordsRoute
  '/_admin/seo-local': typeof AdminSeoLocalRoute
  '/_admin/seo-targets': typeof AdminSeoTargetsRoute
  '/_admin/seo-technical': typeof AdminSeoTechnicalRoute
  '/_admin/users': typeof AdminUsersRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/facilities/$slug': typeof FacilitiesSlugRoute
  '/_admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/facilities': typeof FacilitiesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/_admin/blog-comments/$commentId': typeof AdminBlogCommentsCommentIdRoute
  '/_admin/profile-requests/$requestId': typeof AdminProfileRequestsRequestIdRoute
  '/_admin/seo-keyword/$keywordId': typeof AdminSeoKeywordKeywordIdRoute
  '/_admin/seo-target/$targetId': typeof AdminSeoTargetTargetIdRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/doctor-profile-image': typeof ApiPublicDoctorProfileImageRoute
  '/api/public/doctor-vcard': typeof ApiPublicDoctorVcardRoute
  '/services/hospital/$slug': typeof ServicesHospitalSlugRoute
  '/services/professional/$slug': typeof ServicesProfessionalSlugRoute
  '/_admin/blog-comments': typeof AdminBlogCommentsIndexRoute
  '/_admin/blog': typeof AdminBlogIndexRoute
  '/_admin/departments': typeof AdminDepartmentsIndexRoute
  '/_admin/doctors': typeof AdminDoctorsIndexRoute
  '/_admin/blog/$postId/$section': typeof AdminBlogPostIdSectionRoute
  '/_admin/content/$contentType/$recordId': typeof AdminContentContentTypeRecordIdRoute
  '/_admin/departments/$departmentId/$section': typeof AdminDepartmentsDepartmentIdSectionRoute
  '/_admin/doctors/$doctorId/$section': typeof AdminDoctorsDoctorIdSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/doctors': typeof DoctorsRouteWithChildren
  '/facilities': typeof FacilitiesRouteWithChildren
  '/faq': typeof FaqRoute
  '/media': typeof MediaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/blog': typeof AdminBlogRouteWithChildren
  '/_admin/blog-comments': typeof AdminBlogCommentsRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/departments': typeof AdminDepartmentsRouteWithChildren
  '/_admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/_admin/enquiries': typeof AdminEnquiriesRoute
  '/_admin/facilities': typeof AdminFacilitiesRoute
  '/_admin/faq-categories': typeof AdminFaqCategoriesRoute
  '/_admin/faqs': typeof AdminFaqsRoute
  '/_admin/hospital-services': typeof AdminHospitalServicesRoute
  '/_admin/locations': typeof AdminLocationsRoute
  '/_admin/login': typeof AdminLoginRoute
  '/_admin/media': typeof AdminMediaRoute
  '/_admin/navigation': typeof AdminNavigationRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/pages': typeof AdminPagesRoute
  '/_admin/professional-services': typeof AdminProfessionalServicesRoute
  '/_admin/profile-requests': typeof AdminProfileRequestsRouteWithChildren
  '/_admin/reviews': typeof AdminReviewsRoute
  '/_admin/seo': typeof AdminSeoRoute
  '/_admin/seo-analytics': typeof AdminSeoAnalyticsRoute
  '/_admin/seo-audit': typeof AdminSeoAuditRoute
  '/_admin/seo-history': typeof AdminSeoHistoryRoute
  '/_admin/seo-keywords': typeof AdminSeoKeywordsRoute
  '/_admin/seo-local': typeof AdminSeoLocalRoute
  '/_admin/seo-targets': typeof AdminSeoTargetsRoute
  '/_admin/seo-technical': typeof AdminSeoTechnicalRoute
  '/_admin/users': typeof AdminUsersRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/facilities/$slug': typeof FacilitiesSlugRoute
  '/_admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/facilities/': typeof FacilitiesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_admin/blog-comments/$commentId': typeof AdminBlogCommentsCommentIdRoute
  '/_admin/profile-requests/$requestId': typeof AdminProfileRequestsRequestIdRoute
  '/_admin/seo-keyword/$keywordId': typeof AdminSeoKeywordKeywordIdRoute
  '/_admin/seo-target/$targetId': typeof AdminSeoTargetTargetIdRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/doctor-profile-image': typeof ApiPublicDoctorProfileImageRoute
  '/api/public/doctor-vcard': typeof ApiPublicDoctorVcardRoute
  '/services/hospital/$slug': typeof ServicesHospitalSlugRoute
  '/services/professional/$slug': typeof ServicesProfessionalSlugRoute
  '/_admin/blog-comments/': typeof AdminBlogCommentsIndexRoute
  '/_admin/blog/': typeof AdminBlogIndexRoute
  '/_admin/departments/': typeof AdminDepartmentsIndexRoute
  '/_admin/doctors/': typeof AdminDoctorsIndexRoute
  '/_admin/blog/$postId/$section': typeof AdminBlogPostIdSectionRoute
  '/_admin/content/$contentType/$recordId': typeof AdminContentContentTypeRecordIdRoute
  '/_admin/departments/$departmentId/$section': typeof AdminDepartmentsDepartmentIdSectionRoute
  '/_admin/doctors/$doctorId/$section': typeof AdminDoctorsDoctorIdSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_admin'
    | '/about'
    | '/blog'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/facilities'
    | '/faq'
    | '/media'
    | '/privacy-policy'
    | '/reviews'
    | '/services'
    | '/terms-and-conditions'
    | '/_admin/audit-logs'
    | '/_admin/blog'
    | '/_admin/blog-comments'
    | '/_admin/dashboard'
    | '/_admin/departments'
    | '/_admin/doctors'
    | '/_admin/enquiries'
    | '/_admin/facilities'
    | '/_admin/faq-categories'
    | '/_admin/faqs'
    | '/_admin/hospital-services'
    | '/_admin/locations'
    | '/_admin/login'
    | '/_admin/media'
    | '/_admin/navigation'
    | '/_admin/notifications'
    | '/_admin/pages'
    | '/_admin/professional-services'
    | '/_admin/profile-requests'
    | '/_admin/reviews'
    | '/_admin/seo'
    | '/_admin/seo-analytics'
    | '/_admin/seo-audit'
    | '/_admin/seo-history'
    | '/_admin/seo-keywords'
    | '/_admin/seo-local'
    | '/_admin/seo-targets'
    | '/_admin/seo-technical'
    | '/_admin/users'
    | '/blog/$slug'
    | '/departments/$slug'
    | '/doctors/$slug'
    | '/facilities/$slug'
    | '/_admin/'
    | '/blog/'
    | '/departments/'
    | '/doctors/'
    | '/facilities/'
    | '/services/'
    | '/_admin/blog-comments/$commentId'
    | '/_admin/profile-requests/$requestId'
    | '/_admin/seo-keyword/$keywordId'
    | '/_admin/seo-target/$targetId'
    | '/_admin/users/$userId'
    | '/api/public/doctor-profile-image'
    | '/api/public/doctor-vcard'
    | '/services/hospital/$slug'
    | '/services/professional/$slug'
    | '/_admin/blog-comments/'
    | '/_admin/blog/'
    | '/_admin/departments/'
    | '/_admin/doctors/'
    | '/_admin/blog/$postId/$section'
    | '/_admin/content/$contentType/$recordId'
    | '/_admin/departments/$departmentId/$section'
    | '/_admin/doctors/$doctorId/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/media'
    | '/privacy-policy'
    | '/reviews'
    | '/terms-and-conditions'
    | '/_admin/audit-logs'
    | '/_admin/dashboard'
    | '/_admin/enquiries'
    | '/_admin/facilities'
    | '/_admin/faq-categories'
    | '/_admin/faqs'
    | '/_admin/hospital-services'
    | '/_admin/locations'
    | '/_admin/login'
    | '/_admin/media'
    | '/_admin/navigation'
    | '/_admin/notifications'
    | '/_admin/pages'
    | '/_admin/professional-services'
    | '/_admin/profile-requests'
    | '/_admin/reviews'
    | '/_admin/seo'
    | '/_admin/seo-analytics'
    | '/_admin/seo-audit'
    | '/_admin/seo-history'
    | '/_admin/seo-keywords'
    | '/_admin/seo-local'
    | '/_admin/seo-targets'
    | '/_admin/seo-technical'
    | '/_admin/users'
    | '/blog/$slug'
    | '/departments/$slug'
    | '/doctors/$slug'
    | '/facilities/$slug'
    | '/_admin'
    | '/blog'
    | '/departments'
    | '/doctors'
    | '/facilities'
    | '/services'
    | '/_admin/blog-comments/$commentId'
    | '/_admin/profile-requests/$requestId'
    | '/_admin/seo-keyword/$keywordId'
    | '/_admin/seo-target/$targetId'
    | '/_admin/users/$userId'
    | '/api/public/doctor-profile-image'
    | '/api/public/doctor-vcard'
    | '/services/hospital/$slug'
    | '/services/professional/$slug'
    | '/_admin/blog-comments'
    | '/_admin/blog'
    | '/_admin/departments'
    | '/_admin/doctors'
    | '/_admin/blog/$postId/$section'
    | '/_admin/content/$contentType/$recordId'
    | '/_admin/departments/$departmentId/$section'
    | '/_admin/doctors/$doctorId/$section'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/blog'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/facilities'
    | '/faq'
    | '/media'
    | '/privacy-policy'
    | '/reviews'
    | '/services'
    | '/terms-and-conditions'
    | '/_admin/audit-logs'
    | '/_admin/blog'
    | '/_admin/blog-comments'
    | '/_admin/dashboard'
    | '/_admin/departments'
    | '/_admin/doctors'
    | '/_admin/enquiries'
    | '/_admin/facilities'
    | '/_admin/faq-categories'
    | '/_admin/faqs'
    | '/_admin/hospital-services'
    | '/_admin/locations'
    | '/_admin/login'
    | '/_admin/media'
    | '/_admin/navigation'
    | '/_admin/notifications'
    | '/_admin/pages'
    | '/_admin/professional-services'
    | '/_admin/profile-requests'
    | '/_admin/reviews'
    | '/_admin/seo'
    | '/_admin/seo-analytics'
    | '/_admin/seo-audit'
    | '/_admin/seo-history'
    | '/_admin/seo-keywords'
    | '/_admin/seo-local'
    | '/_admin/seo-targets'
    | '/_admin/seo-technical'
    | '/_admin/users'
    | '/blog/$slug'
    | '/departments/$slug'
    | '/doctors/$slug'
    | '/facilities/$slug'
    | '/_admin/'
    | '/blog/'
    | '/departments/'
    | '/doctors/'
    | '/facilities/'
    | '/services/'
    | '/_admin/blog-comments/$commentId'
    | '/_admin/profile-requests/$requestId'
    | '/_admin/seo-keyword/$keywordId'
    | '/_admin/seo-target/$targetId'
    | '/_admin/users/$userId'
    | '/api/public/doctor-profile-image'
    | '/api/public/doctor-vcard'
    | '/services/hospital/$slug'
    | '/services/professional/$slug'
    | '/_admin/blog-comments/'
    | '/_admin/blog/'
    | '/_admin/departments/'
    | '/_admin/doctors/'
    | '/_admin/blog/$postId/$section'
    | '/_admin/content/$contentType/$recordId'
    | '/_admin/departments/$departmentId/$section'
    | '/_admin/doctors/$doctorId/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  DoctorsRoute: typeof DoctorsRouteWithChildren
  FacilitiesRoute: typeof FacilitiesRouteWithChildren
  FaqRoute: typeof FaqRoute
  MediaRoute: typeof MediaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiPublicDoctorProfileImageRoute: typeof ApiPublicDoctorProfileImageRoute
  ApiPublicDoctorVcardRoute: typeof ApiPublicDoctorVcardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: '/_admin'
      fullPath: '/_admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/_admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-logs': {
      id: '/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/_admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/blog': {
      id: '/_admin/blog'
      path: '/blog'
      fullPath: '/_admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/blog-comments': {
      id: '/_admin/blog-comments'
      path: '/blog-comments'
      fullPath: '/_admin/blog-comments'
      preLoaderRoute: typeof AdminBlogCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/_admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/departments': {
      id: '/_admin/departments'
      path: '/departments'
      fullPath: '/_admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/doctors': {
      id: '/_admin/doctors'
      path: '/doctors'
      fullPath: '/_admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/enquiries': {
      id: '/_admin/enquiries'
      path: '/enquiries'
      fullPath: '/_admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/facilities': {
      id: '/_admin/facilities'
      path: '/facilities'
      fullPath: '/_admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/faq-categories': {
      id: '/_admin/faq-categories'
      path: '/faq-categories'
      fullPath: '/_admin/faq-categories'
      preLoaderRoute: typeof AdminFaqCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/faqs': {
      id: '/_admin/faqs'
      path: '/faqs'
      fullPath: '/_admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/hospital-services': {
      id: '/_admin/hospital-services'
      path: '/hospital-services'
      fullPath: '/_admin/hospital-services'
      preLoaderRoute: typeof AdminHospitalServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locations': {
      id: '/_admin/locations'
      path: '/locations'
      fullPath: '/_admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/login': {
      id: '/_admin/login'
      path: '/login'
      fullPath: '/_admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/media': {
      id: '/_admin/media'
      path: '/media'
      fullPath: '/_admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/navigation': {
      id: '/_admin/navigation'
      path: '/navigation'
      fullPath: '/_admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/_admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pages': {
      id: '/_admin/pages'
      path: '/pages'
      fullPath: '/_admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/professional-services': {
      id: '/_admin/professional-services'
      path: '/professional-services'
      fullPath: '/_admin/professional-services'
      preLoaderRoute: typeof AdminProfessionalServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/profile-requests': {
      id: '/_admin/profile-requests'
      path: '/profile-requests'
      fullPath: '/_admin/profile-requests'
      preLoaderRoute: typeof AdminProfileRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reviews': {
      id: '/_admin/reviews'
      path: '/reviews'
      fullPath: '/_admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seo': {
      id: '/_admin/seo'
      path: '/seo'
      fullPath: '/_admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seo-analytics': {
      id: '/_admin/seo-analytics'
      path: '/seo-analytics'
      fullPath: '/_admin/seo-analytics'
      preLoaderRoute: typeof AdminSeoAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seo-audit': {
      id: '/_admin/seo-audit'
      path: '/seo-audit'
      fullPath: '/_admin/seo-audit'
      preLoaderRoute: typeof AdminSeoAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seo-history': {
      id: '/_admin/seo-history'
      path: '/seo-history'
      fullPath: '/_admin/seo-history'
      preLoaderRoute: typeof AdminSeoHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seo-keywords': {
      id: '/_admin/seo-keywords'
      path: '/seo-keywords'
      fullPath: '/_admin/seo-keywords'
      preLoaderRoute: typeof AdminSeoKeywordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seo-local': {
      id: '/_admin/seo-local'
      path: '/seo-local'
      fullPath: '/_admin/seo-local'
      preLoaderRoute: typeof AdminSeoLocalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seo-targets': {
      id: '/_admin/seo-targets'
      path: '/seo-targets'
      fullPath: '/_admin/seo-targets'
      preLoaderRoute: typeof AdminSeoTargetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seo-technical': {
      id: '/_admin/seo-technical'
      path: '/seo-technical'
      fullPath: '/_admin/seo-technical'
      preLoaderRoute: typeof AdminSeoTechnicalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/_admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/departments/': {
      id: '/departments/'
      path: '/'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof DoctorsRoute
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof DoctorsRoute
    }
    '/facilities/': {
      id: '/facilities/'
      path: '/'
      fullPath: '/facilities/'
      preLoaderRoute: typeof FacilitiesIndexRouteImport
      parentRoute: typeof FacilitiesRoute
    }
    '/facilities/$slug': {
      id: '/facilities/$slug'
      path: '/$slug'
      fullPath: '/facilities/$slug'
      preLoaderRoute: typeof FacilitiesSlugRouteImport
      parentRoute: typeof FacilitiesRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_admin/blog-comments/': {
      id: '/_admin/blog-comments/'
      path: '/'
      fullPath: '/_admin/blog-comments/'
      preLoaderRoute: typeof AdminBlogCommentsIndexRouteImport
      parentRoute: typeof AdminBlogCommentsRoute
    }
    '/_admin/blog-comments/$commentId': {
      id: '/_admin/blog-comments/$commentId'
      path: '/$commentId'
      fullPath: '/_admin/blog-comments/$commentId'
      preLoaderRoute: typeof AdminBlogCommentsCommentIdRouteImport
      parentRoute: typeof AdminBlogCommentsRoute
    }
    '/_admin/blog/': {
      id: '/_admin/blog/'
      path: '/'
      fullPath: '/_admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/_admin/departments/': {
      id: '/_admin/departments/'
      path: '/'
      fullPath: '/_admin/departments/'
      preLoaderRoute: typeof AdminDepartmentsIndexRouteImport
      parentRoute: typeof AdminDepartmentsRoute
    }
    '/_admin/doctors/': {
      id: '/_admin/doctors/'
      path: '/'
      fullPath: '/_admin/doctors/'
      preLoaderRoute: typeof AdminDoctorsIndexRouteImport
      parentRoute: typeof AdminDoctorsRoute
    }
    '/_admin/profile-requests/$requestId': {
      id: '/_admin/profile-requests/$requestId'
      path: '/$requestId'
      fullPath: '/_admin/profile-requests/$requestId'
      preLoaderRoute: typeof AdminProfileRequestsRequestIdRouteImport
      parentRoute: typeof AdminProfileRequestsRoute
    }
    '/_admin/seo-keyword/$keywordId': {
      id: '/_admin/seo-keyword/$keywordId'
      path: '/seo-keyword/$keywordId'
      fullPath: '/_admin/seo-keyword/$keywordId'
      preLoaderRoute: typeof AdminSeoKeywordKeywordIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/seo-target/$targetId': {
      id: '/_admin/seo-target/$targetId'
      path: '/seo-target/$targetId'
      fullPath: '/_admin/seo-target/$targetId'
      preLoaderRoute: typeof AdminSeoTargetTargetIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/$userId': {
      id: '/_admin/users/$userId'
      path: '/$userId'
      fullPath: '/_admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/api/public/doctor-profile-image': {
      id: '/api/public/doctor-profile-image'
      path: '/api/public/doctor-profile-image'
      fullPath: '/api/public/doctor-profile-image'
      preLoaderRoute: typeof ApiPublicDoctorProfileImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/doctor-vcard': {
      id: '/api/public/doctor-vcard'
      path: '/api/public/doctor-vcard'
      fullPath: '/api/public/doctor-vcard'
      preLoaderRoute: typeof ApiPublicDoctorVcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hospital/$slug': {
      id: '/services/hospital/$slug'
      path: '/hospital/$slug'
      fullPath: '/services/hospital/$slug'
      preLoaderRoute: typeof ServicesHospitalSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/professional/$slug': {
      id: '/services/professional/$slug'
      path: '/professional/$slug'
      fullPath: '/services/professional/$slug'
      preLoaderRoute: typeof ServicesProfessionalSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_admin/blog/$postId/$section': {
      id: '/_admin/blog/$postId/$section'
      path: '/$postId/$section'
      fullPath: '/_admin/blog/$postId/$section'
      preLoaderRoute: typeof AdminBlogPostIdSectionRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/_admin/content/$contentType/$recordId': {
      id: '/_admin/content/$contentType/$recordId'
      path: '/content/$contentType/$recordId'
      fullPath: '/_admin/content/$contentType/$recordId'
      preLoaderRoute: typeof AdminContentContentTypeRecordIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/departments/$departmentId/$section': {
      id: '/_admin/departments/$departmentId/$section'
      path: '/$departmentId/$section'
      fullPath: '/_admin/departments/$departmentId/$section'
      preLoaderRoute: typeof AdminDepartmentsDepartmentIdSectionRouteImport
      parentRoute: typeof AdminDepartmentsRoute
    }
    '/_admin/doctors/$doctorId/$section': {
      id: '/_admin/doctors/$doctorId/$section'
      path: '/$doctorId/$section'
      fullPath: '/_admin/doctors/$doctorId/$section'
      preLoaderRoute: typeof AdminDoctorsDoctorIdSectionRouteImport
      parentRoute: typeof AdminDoctorsRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBlogPostIdSectionRoute: typeof AdminBlogPostIdSectionRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBlogPostIdSectionRoute: AdminBlogPostIdSectionRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminBlogCommentsRouteChildren {
  AdminBlogCommentsCommentIdRoute: typeof AdminBlogCommentsCommentIdRoute
  AdminBlogCommentsIndexRoute: typeof AdminBlogCommentsIndexRoute
}

const AdminBlogCommentsRouteChildren: AdminBlogCommentsRouteChildren = {
  AdminBlogCommentsCommentIdRoute: AdminBlogCommentsCommentIdRoute,
  AdminBlogCommentsIndexRoute: AdminBlogCommentsIndexRoute,
}

const AdminBlogCommentsRouteWithChildren =
  AdminBlogCommentsRoute._addFileChildren(AdminBlogCommentsRouteChildren)

interface AdminDepartmentsRouteChildren {
  AdminDepartmentsIndexRoute: typeof AdminDepartmentsIndexRoute
  AdminDepartmentsDepartmentIdSectionRoute: typeof AdminDepartmentsDepartmentIdSectionRoute
}

const AdminDepartmentsRouteChildren: AdminDepartmentsRouteChildren = {
  AdminDepartmentsIndexRoute: AdminDepartmentsIndexRoute,
  AdminDepartmentsDepartmentIdSectionRoute:
    AdminDepartmentsDepartmentIdSectionRoute,
}

const AdminDepartmentsRouteWithChildren =
  AdminDepartmentsRoute._addFileChildren(AdminDepartmentsRouteChildren)

interface AdminDoctorsRouteChildren {
  AdminDoctorsIndexRoute: typeof AdminDoctorsIndexRoute
  AdminDoctorsDoctorIdSectionRoute: typeof AdminDoctorsDoctorIdSectionRoute
}

const AdminDoctorsRouteChildren: AdminDoctorsRouteChildren = {
  AdminDoctorsIndexRoute: AdminDoctorsIndexRoute,
  AdminDoctorsDoctorIdSectionRoute: AdminDoctorsDoctorIdSectionRoute,
}

const AdminDoctorsRouteWithChildren = AdminDoctorsRoute._addFileChildren(
  AdminDoctorsRouteChildren,
)

interface AdminProfileRequestsRouteChildren {
  AdminProfileRequestsRequestIdRoute: typeof AdminProfileRequestsRequestIdRoute
}

const AdminProfileRequestsRouteChildren: AdminProfileRequestsRouteChildren = {
  AdminProfileRequestsRequestIdRoute: AdminProfileRequestsRequestIdRoute,
}

const AdminProfileRequestsRouteWithChildren =
  AdminProfileRequestsRoute._addFileChildren(AdminProfileRequestsRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminBlogCommentsRoute: typeof AdminBlogCommentsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRouteWithChildren
  AdminDoctorsRoute: typeof AdminDoctorsRouteWithChildren
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminFaqCategoriesRoute: typeof AdminFaqCategoriesRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminHospitalServicesRoute: typeof AdminHospitalServicesRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminProfessionalServicesRoute: typeof AdminProfessionalServicesRoute
  AdminProfileRequestsRoute: typeof AdminProfileRequestsRouteWithChildren
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSeoAnalyticsRoute: typeof AdminSeoAnalyticsRoute
  AdminSeoAuditRoute: typeof AdminSeoAuditRoute
  AdminSeoHistoryRoute: typeof AdminSeoHistoryRoute
  AdminSeoKeywordsRoute: typeof AdminSeoKeywordsRoute
  AdminSeoLocalRoute: typeof AdminSeoLocalRoute
  AdminSeoTargetsRoute: typeof AdminSeoTargetsRoute
  AdminSeoTechnicalRoute: typeof AdminSeoTechnicalRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSeoKeywordKeywordIdRoute: typeof AdminSeoKeywordKeywordIdRoute
  AdminSeoTargetTargetIdRoute: typeof AdminSeoTargetTargetIdRoute
  AdminContentContentTypeRecordIdRoute: typeof AdminContentContentTypeRecordIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminBlogCommentsRoute: AdminBlogCommentsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRouteWithChildren,
  AdminDoctorsRoute: AdminDoctorsRouteWithChildren,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminFaqCategoriesRoute: AdminFaqCategoriesRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminHospitalServicesRoute: AdminHospitalServicesRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminProfessionalServicesRoute: AdminProfessionalServicesRoute,
  AdminProfileRequestsRoute: AdminProfileRequestsRouteWithChildren,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSeoAnalyticsRoute: AdminSeoAnalyticsRoute,
  AdminSeoAuditRoute: AdminSeoAuditRoute,
  AdminSeoHistoryRoute: AdminSeoHistoryRoute,
  AdminSeoKeywordsRoute: AdminSeoKeywordsRoute,
  AdminSeoLocalRoute: AdminSeoLocalRoute,
  AdminSeoTargetsRoute: AdminSeoTargetsRoute,
  AdminSeoTechnicalRoute: AdminSeoTechnicalRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminSeoKeywordKeywordIdRoute: AdminSeoKeywordKeywordIdRoute,
  AdminSeoTargetTargetIdRoute: AdminSeoTargetTargetIdRoute,
  AdminContentContentTypeRecordIdRoute: AdminContentContentTypeRecordIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DepartmentsRouteChildren {
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsSlugRoute: DepartmentsSlugRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

interface DoctorsRouteChildren {
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

const DoctorsRouteChildren: DoctorsRouteChildren = {
  DoctorsSlugRoute: DoctorsSlugRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}

const DoctorsRouteWithChildren =
  DoctorsRoute._addFileChildren(DoctorsRouteChildren)

interface FacilitiesRouteChildren {
  FacilitiesSlugRoute: typeof FacilitiesSlugRoute
  FacilitiesIndexRoute: typeof FacilitiesIndexRoute
}

const FacilitiesRouteChildren: FacilitiesRouteChildren = {
  FacilitiesSlugRoute: FacilitiesSlugRoute,
  FacilitiesIndexRoute: FacilitiesIndexRoute,
}

const FacilitiesRouteWithChildren = FacilitiesRoute._addFileChildren(
  FacilitiesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesHospitalSlugRoute: typeof ServicesHospitalSlugRoute
  ServicesProfessionalSlugRoute: typeof ServicesProfessionalSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesHospitalSlugRoute: ServicesHospitalSlugRoute,
  ServicesProfessionalSlugRoute: ServicesProfessionalSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  DoctorsRoute: DoctorsRouteWithChildren,
  FacilitiesRoute: FacilitiesRouteWithChildren,
  FaqRoute: FaqRoute,
  MediaRoute: MediaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiPublicDoctorProfileImageRoute: ApiPublicDoctorProfileImageRoute,
  ApiPublicDoctorVcardRoute: ApiPublicDoctorVcardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
